package com.pro.snap.vo;

import lombok.AllArgsConstructor;
import lombok.ToString;
import lombok.Getter;

@Getter
@ToString
@AllArgsConstructor
public enum RespBeanEnum {
    // 通用
    SUCCESS(200, "SUCCESS"),
    ERROR(500, "SERVER EXCEPTION"),
    // 登录5002
    LOGIN_ERROR(500210, "WRONG ACCOUNT/PASSWORD"),
    MOBILE_ERROR(500211, "WRONG PHONE NUMBERS FORMAT"),
    NOTFOUND_ERROR(500209, "USER NOT FOUND"),
    BIND_ERROR(500212, "ARGUMENT INVALID EXCEPTION"),
    MOBILE_NOT_EXIST(500213, "PHONE NUMBERS NOT EXIST"),
    PASSWORD_UPDATE_FAILED(500214, "PASSWORD UPDATE FAILED"),
    USER_NOT_EXIST(500215, "USER NOT EXIST"),

    //秒杀5005
    EMPTY_STOCK(500500, "OUT OF STOCK"),
    REPEAT_ERROR(500501, "LIMITED TO 1 PER CUSTOMER"),
    ILLEGAL_REQUEST(500502, "ILLEGAL REQUEST"),
    WRONG_CAPTCHA(500503, "WRONG CAPTCHA"),
    FREQUENT_ACCESS(500504, "TOO FREQUENT ACCESS"),

    //订单模块5003
    ORDER_NOT_EXIST(500300, "ORDER NOT EXIST"),
    ZZZZZZZZZ(500399, "LIMITED TO 1 PER CUSTOMER")
    ;

    private final Integer code;
    private final String message;
}
